import { Platform } from "react-native";
import Config from "react-native-config";

export const CONFIG_DATA = {
  TSC_COMPILE_ON_ERROR: Config.TSC_COMPILE_ON_ERROR,
  EXTEND_ESLINT: Config.EXTEND_ESLINT,
  DISABLE_ESLINT_PLUGIN: Config.DISABLE_ESLINT_PLUGIN,
  REACT_APP_CALL_MORALIS_API_KEY: Config.REACT_APP_CALL_MORALIS_API_KEY,
  REACT_APP_FIREBASE_API_KEY: Config.REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN: Config.REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_DATABASE_URL: Config.REACT_APP_FIREBASE_DATABASE_URL,
  REACT_APP_FIREBASE_PROJECT_ID: Config.REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET: Config.REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGNING_SENDER_ID:
    Config.REACT_APP_FIREBASE_MESSAGNING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID: Config.REACT_APP_FIREBASE_APP_ID,
  REACT_APP_API_URL: Config.REACT_APP_API_URL,
  REACT_APP_API_LINK: Config.REACT_APP_API_LINK,
  REACT_APP_STRIPE_KEY: Config.REACT_APP_STRIPE_KEY,
  REACT_APP_JSON_RPC_URL: Config.REACT_APP_JSON_RPC_URL,
  REACT_APP_QR_URL: Config.REACT_APP_QR_URL,
  REACT_APP_DINT_CONTRACT_ADDR: Config.REACT_APP_DINT_CONTRACT_ADDR,
  REACT_APP_COINGECKO_API: Config.REACT_APP_COINGECKO_API,
  REACT_APP_X_CG_PRO_API_KEY: Config.REACT_APP_X_CG_PRO_API_KEY,
  REACT_APP_POLYGON_EXPLORER: Config.REACT_APP_POLYGON_EXPLORER,
  REACT_APP_WSS: Config.REACT_APP_WSS,
  REACT_APP_GOOGLE_MAPS_API_KEY: Config.REACT_APP_GOOGLE_MAPS_API_KEY,
};

export const isAndroid = Platform.OS === "android";
